inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
   - 'bin/*'
   - 'db/*'
   - 'config/**/*'
   - 'vendor/bundle/**/*'
   - 'node_modules/**/*'
   - 'Guardfile'
  NewCops: enable
Style/Documentation:
  Enabled: false
Lint/Debugger:
  AutoCorrect: false
Layout/LineLength:
  Max: 120
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Naming/MemoizedInstanceVariableName:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
