inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql
  - rubocop-rspec_rails
AllCops:
  Exclude:
   - 'bin/*'
   - 'db/*'
   - 'config/**/*'
   - 'vendor/bundle/**/*'
   - 'node_modules/**/*'
   - 'Guardfile'
  NewCops: enable
Style/Documentation:
  Enabled: false
Lint/Debugger:
  AutoCorrect: false
Layout/LineLength:
  Max: 120
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Naming/MemoizedInstanceVariableName:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
GraphQL/FieldDescription:
  Enabled: false
GraphQL/ObjectDescription:
  Enabled: false
GraphQL/ArgumentDescription:
  Enabled: false
GraphQL/ExtractType:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/ExampleLength:
  Max: 10