development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: church_resources_development
  host: localhost
  username: postgres
  password: <%= ENV.fetch('POSTGRES_PASSWORD', nil) %>
  port: 5432
test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: church_resources_test
  host: localhost
  username: postgres
  password: <%= ENV.fetch('POSTGRES_PASSWORD', nil) %>
  port: 5432