# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

life = Category.create(name: 'Life')
life.topics.create(name: 'Anger')
life.topics.create(name: 'Anxiety')
life.topics.create(name: 'Courage')
life.topics.create(name: 'Death')
life.topics.create(name: 'Encouragement')
life.topics.create(name: 'Faith')
life.topics.create(name: 'Family Discipleship')
life.topics.create(name: 'Fatherhood')
life.topics.create(name: 'Fear')
life.topics.create(name: 'Finances')
life.topics.create(name: 'Forgiveness')
life.topics.create(name: 'Giving')
life.topics.create(name: 'Holiness')
life.topics.create(name: 'Hypocrisy')
life.topics.create(name: 'Identity')
life.topics.create(name: 'Idolatry')
life.topics.create(name: 'Joy')
life.topics.create(name: 'Motherhood')
life.topics.create(name: 'Peace')
life.topics.create(name: 'Persecution')
life.topics.create(name: 'Prayer')
life.topics.create(name: 'Pride')
life.topics.create(name: 'Purity')
life.topics.create(name: 'Relationships')
life.topics.create(name: 'Rest')
life.topics.create(name: 'Speech')
life.topics.create(name: 'Suffering')
life.topics.create(name: 'Wisdom')

culture = Category.create(name: 'Culture')
culture.topics.create(name: 'Abortion')
culture.topics.create(name: 'Gender')
culture.topics.create(name: 'Politics')
culture.topics.create(name: 'Race')
culture.topics.create(name: 'Work')

theology = Category.create(name: 'Theology')
theology.topics.create(name: 'Baptism')
theology.topics.create(name: 'The Bible')
theology.topics.create(name: 'The Birth of Christ')
theology.topics.create(name: 'The Character of God')
theology.topics.create(name: 'Creation')
theology.topics.create(name: 'The Death of Christ')
theology.topics.create(name: 'End Times')
theology.topics.create(name: 'The Fall')
theology.topics.create(name: 'The Gospel')
theology.topics.create(name: 'Heaven & Hell')
theology.topics.create(name: 'The Kingdom of God')
theology.topics.create(name: 'The Law')
theology.topics.create(name: 'The Lord\'s Supper')
theology.topics.create(name: 'The Ministry of Christ')
theology.topics.create(name: 'The Resurrection of Christ')
theology.topics.create(name: 'The Return of Christ')
theology.topics.create(name: 'Salvation')
theology.topics.create(name: 'Sanctification')
theology.topics.create(name: 'Sin')
theology.topics.create(name: 'Sound Doctrine')
theology.topics.create(name: 'The Sovereignty of God')
theology.topics.create(name: 'Spiritual Gifts')
theology.topics.create(name: 'Spiritual Warfare')

church = Category.create(name: 'Church')
church.topics.create(name: 'Church Planting')
church.topics.create(name: 'Community')
church.topics.create(name: 'Discipleship')
church.topics.create(name: 'Discipline')
church.topics.create(name: 'False Teaching')
church.topics.create(name: 'The Gathering')
church.topics.create(name: 'History')
church.topics.create(name: 'Leadership')
church.topics.create(name: 'Membership')
church.topics.create(name: 'Missional Living')
church.topics.create(name: 'Missions')
church.topics.create(name: 'Multisite')
church.topics.create(name: 'Nature of the Church')
church.topics.create(name: 'Service')

Scripture.create(name: 'Exodus')
Scripture.create(name: 'Leviticus')
Scripture.create(name: 'Numbers')
Scripture.create(name: 'Genesis')
Scripture.create(name: 'Deuteronomy')
Scripture.create(name: 'Joshua')
Scripture.create(name: 'Judges')
Scripture.create(name: 'Ruth')
Scripture.create(name: '1 Samuel')
Scripture.create(name: '2 Samuel')
Scripture.create(name: '1 Kings')
Scripture.create(name: '2 Kings')
Scripture.create(name: '1 Chronicles')
Scripture.create(name: '2 Chronicles')
Scripture.create(name: 'Ezra')
Scripture.create(name: 'Nehemiah')
Scripture.create(name: 'Esther')
Scripture.create(name: 'Job')
Scripture.create(name: 'Psalms')
Scripture.create(name: 'Proverbs')
Scripture.create(name: 'Ecclesiastes')
Scripture.create(name: 'Song of Solomon')
Scripture.create(name: 'Isaiah')
Scripture.create(name: 'Jeremiah')
Scripture.create(name: 'Lamentations')
Scripture.create(name: 'Ezekiel')
Scripture.create(name: 'Daniel')
Scripture.create(name: 'Hosea')
Scripture.create(name: 'Joel')
Scripture.create(name: 'Amos')
Scripture.create(name: 'Obadiah')
Scripture.create(name: 'Jonah')
Scripture.create(name: 'Micah')
Scripture.create(name: 'Nahum')
Scripture.create(name: 'Habakkuk')
Scripture.create(name: 'Zephaniah')
Scripture.create(name: 'Haggai')
Scripture.create(name: 'Zechariah')
Scripture.create(name: 'Malachi')
Scripture.create(name: 'Matthew')
Scripture.create(name: 'Mark')
Scripture.create(name: 'Luke')
Scripture.create(name: 'John')
Scripture.create(name: 'Acts')
Scripture.create(name: 'Romans')
Scripture.create(name: '1 Corinthians')
Scripture.create(name: '2 Corinthians')
Scripture.create(name: 'Galatians')
Scripture.create(name: 'Ephesians')
Scripture.create(name: 'Philippians')
Scripture.create(name: 'Colossians')
Scripture.create(name: '1 Thessalonians')
Scripture.create(name: '2 Thessalonians')
Scripture.create(name: '1 Timothy')
Scripture.create(name: '2 Timothy')
Scripture.create(name: 'Titus')
Scripture.create(name: 'Philemon')
Scripture.create(name: 'Hebrews')
Scripture.create(name: 'James')
Scripture.create(name: '1 Peter')
Scripture.create(name: '2 Peter')
Scripture.create(name: '1 John')
Scripture.create(name: '2 John')
Scripture.create(name: '3 John')
Scripture.create(name: 'Jude')
Scripture.create(name: 'Revelation')
